/**
 * Validates local references across documentation Markdown files:
 * - article images `./assets/…` must exist under docs/<lang>/…;
 * - root-absolute images `/assets/…` must exist under public/;
 * - internal `.md` links must point to existing documents.
 *
 * Code fences and inline code are ignored. Exits with code 1 on any violation.
 */
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { listPublicFiles } from '../src/shared/shared-utils.mjs';
import { generatedPublicRelativePaths } from './assets/generated-outputs.mjs';

const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const docsDir = path.join(rootDir, 'docs');
const publicDir = path.join(rootDir, 'public');

const IMAGE_RE = /!\[[^\]]*]\(([^)\s]+)(?:\s+"[^"]*")?\)/g;
const LINK_RE = /(?<!!)\[[^\]]*]\(([^)\s]+)(?:\s+"[^"]*")?\)/g;

const stripCode = (text) =>
  text
    .replace(/^```[\s\S]*?^```/gm, ' ')
    .replace(/`[^`\n]*`/g, ' ');

const isExternal = (target) =>
  /^(?:[a-z][a-z0-9+.-]*:|\/\/|#|mailto:)/i.test(target);

const normalizeDocId = (linkPath, lang, articleRelDir) => {
  const normalized = linkPath.replace(/\\/g, '/').replace(/\.md$/i, '');

  if (normalized.startsWith('/')) {
    return normalized.replace(/^\/+/, '').replace(/^docs\//, '').replace(/^(?:ru|en)\//, '');
  }

  const joined = articleRelDir ? `${articleRelDir}/${normalized}` : normalized;

  const segments = [];
  for (const segment of joined.split('/')) {
    if (!segment || segment === '.') continue;
    if (segment === '..') segments.pop();
    else segments.push(segment);
  }

  return segments.join('/').replace(new RegExp(`^${lang}/`), '');
};

const resolveArticleAsset = (src, lang, articleRelDir) => {
  const clean = src.split('#')[0].split('?')[0].replace(/\\/g, '/');

  if (clean.startsWith('/')) {
    return { kind: 'public', relPath: clean.replace(/^\/+/, '') };
  }

  const joined = articleRelDir ? `${articleRelDir}/${clean}` : clean;
  const segments = [];
  for (const segment of joined.split('/')) {
    if (!segment || segment === '.') continue;
    if (segment === '..') segments.pop();
    else segments.push(segment);
  }

  return { kind: 'docs', relPath: `${lang}/${segments.join('/')}` };
};

const markdownFiles = (await listPublicFiles(fs, docsDir, { joinPath: path.join }))
  .filter((file) => /\.md$/i.test(file));

const violations = [];

for (const file of markdownFiles) {
  const relUnderDocs = path.relative(docsDir, file).replace(/\\/g, '/');
  const lang = relUnderDocs.split('/')[0];
  const articleRelDir = path.posix.dirname(relUnderDocs).split('/').slice(1).filter(Boolean).join('/');
  const text = stripCode(await fs.readFile(file, 'utf8'));

  for (const match of text.matchAll(IMAGE_RE)) {
    const src = match[1];
    if (isExternal(src)) continue;

    const resolved = resolveArticleAsset(src, lang, articleRelDir);
    const base = resolved.kind === 'public' ? publicDir : docsDir;
    const target = path.join(base, ...resolved.relPath.split('/'));

    try {
      await fs.access(target);
    } catch {
      // Generated by optimize-assets from branding/ during build; absent on a
      // fresh checkout by design, so their absence is not a broken reference.
      const isGenerated =
        resolved.kind === 'public' && generatedPublicRelativePaths.has(resolved.relPath);

      if (!isGenerated) {
        violations.push(`${relUnderDocs}: missing image "${src}" -> ${resolved.kind}/${resolved.relPath}`);
      }
    }
  }

  for (const match of text.matchAll(LINK_RE)) {
    const target = match[1];
    if (isExternal(target)) continue;

    const linkPath = target.split('#')[0];
    if (!linkPath) continue;

    if (/\.md$/i.test(linkPath)) {
      const id = normalizeDocId(linkPath, lang, articleRelDir);
      const docFile = path.join(docsDir, lang, ...id.split('/')) + '.md';
      try {
        await fs.access(docFile);
      } catch {
        violations.push(`${relUnderDocs}: broken doc link "${target}" -> docs/${lang}/${id}.md`);
      }
      continue;
    }

    const resolved = resolveArticleAsset(linkPath, lang, articleRelDir);
    const base = resolved.kind === 'public' ? publicDir : docsDir;
    const assetPath = path.join(base, ...resolved.relPath.split('/'));
    try {
      await fs.access(assetPath);
    } catch {
      const isGenerated =
        resolved.kind === 'public' && generatedPublicRelativePaths.has(resolved.relPath);

      if (!isGenerated) {
        violations.push(`${relUnderDocs}: missing linked file "${target}"`);
      }
    }
  }
}

if (violations.length) {
  console.error(`Found ${violations.length} broken reference(s):`);
  for (const violation of violations) console.error(`  - ${violation}`);
  process.exit(1);
}

console.log(`Checked ${markdownFiles.length} Markdown files: all references are valid.`);
